In [1]:
import pandas as pd

In [6]:
# The path to our CSV file
file = "Resources/KickstarterData.csv"
# Read our Kickstarter data into pandas
Kick_df = pd.read_csv(file)
Kick_df.head()

,id,photo,name,blurb,goal,pledged,state,slug,disable_communication,country,...,location,category,profile,spotlight,urls,source_url,friends,is_starred,is_backing,permissions
0,1645666704,"{""small"":""https://ksr-ugc.imgix.net/assets/012...",The Class Act Players Theatre Company Presents...,The Class Act Players put on another one of th...,1500.0,2925.0,successful,the-class-act-players-theatre-company-presents...,False,US,...,"{""country"":""US"",""urls"":{""web"":{""discover"":""htt...","{""urls"":{""web"":{""discover"":""http://www.kicksta...","{""background_image_opacity"":0.8,""should_show_f...",True,"{""web"":{""project"":""https://www.kickstarter.com...",https://www.kickstarter.com/discover/categorie...,NaN,NaN,NaN,NaN
1,874638240,"{""small"":""https://ksr-ugc.imgix.net/assets/012...",MR INCREDIBLE by Camilla Whitehill - VAULT Fes...,"A brand new play about love and entitlement, b...",2500.0,2936.0,successful,mr-incredible-by-camilla-whitehill-vault-festival,False,GB,...,"{""country"":""GB"",""urls"":{""web"":{""discover"":""htt...","{""urls"":{""web"":{""discover"":""http://www.kicksta...","{""background_image_opacity"":0.8,""should_show_f...",True,"{""web"":{""project"":""https://www.kickstarter.com...",https://www.kickstarter.com/discover/categorie...,NaN,NaN,NaN,NaN
2,247074984,"{""small"":""https://ksr-ugc.imgix.net/assets/012...",RUN,Yonni's pissed off in a world filled with scho...,1000.0,1200.0,successful,run-10,False,GB,...,"{""country"":""GB"",""urls"":{""web"":{""discover"":""htt...","{""urls"":{""web"":{""discover"":""http://www.kicksta...","{""background_image_opacity"":0.8,""should_show_f...",True,"{""web"":{""project"":""https://www.kickstarter.com...",https://www.kickstarter.com/discover/categorie...,NaN,NaN,NaN,NaN
3,1941196813,"{""small"":""https://ksr-ugc.imgix.net/assets/012...",9th International Meeting of Youth Theatre sap...,27. April bis 1. Mai 2016 in Brixen/Südtirol/I...,2000.0,2135.0,successful,9th-international-meeting-of-youth-theatre-sap...,False,IT,...,"{""country"":""IT"",""urls"":{""web"":{""discover"":""htt...","{""urls"":{""web"":{""discover"":""http://www.kicksta...","{""background_image_opacity"":0.8,""should_show_f...",True,"{""web"":{""project"":""https://www.kickstarter.com...",https://www.kickstarter.com/discover/categorie...,NaN,NaN,NaN,NaN
4,421961595,"{""small"":""https://ksr-ugc.imgix.net/assets/012...",Get Conti to the Ed Fringe!,The Italia Conti 2nd years are going to Ed Fri...,1000.0,1250.0,successful,get-conti-to-the-ed-fringe,False,GB,...,"{""country"":""GB"",""urls"":{""web"":{""discover"":""htt...","{""urls"":{""web"":{""discover"":""http://www.kicksta...","{""background_image_opacity"":0.8,""should_show_f...",True,"{""web"":{""project"":""https://www.kickstarter.com...",https://www.kickstarter.com/discover/categorie...,NaN,NaN,NaN,NaN

In [7]:
# Get a list of all of our columns for easy reference
Kick_df.columns

Index(['id', 'photo', 'name', 'blurb', 'goal', 'pledged', 'state', 'slug',
       'disable_communication', 'country', 'currency', 'currency_symbol',
       'currency_trailing_code', 'deadline', 'state_changed_at', 'created_at',
       'launched_at', 'staff_pick', 'is_starrable', 'backers_count',
       'static_usd_rate', 'usd_pledged', 'creator', 'location', 'category',
       'profile', 'spotlight', 'urls', 'source_url', 'friends', 'is_starred',
       'is_backing', 'permissions'],
      dtype='object')

In [9]:
# Extract "name", "goal", "pledged", "state", "country", "staff_pick",
# "backers_count", and "spotlight"
New_df = Kick_df[["name", "goal", "pledged", "state", "country", "staff_pick", "backers_count", "spotlight"]]
New_df

,name,goal,pledged,state,country,staff_pick,backers_count,spotlight
0,The Class Act Players Theatre Company Presents...,1500.0,2925.00,successful,US,False,17,True
1,MR INCREDIBLE by Camilla Whitehill - VAULT Fes...,2500.0,2936.00,successful,GB,True,15,True
2,RUN,1000.0,1200.00,successful,GB,False,30,True
3,9th International Meeting of Youth Theatre sap...,2000.0,2135.00,successful,IT,False,24,True
4,Get Conti to the Ed Fringe!,1000.0,1250.00,successful,GB,False,28,True
5,Somebody Out There Loves Me @ Edinburgh Fringe...,1100.0,1100.00,successful,GB,False,41,True
6,Stand Up & Slam! at the Edinburgh Fringe,1500.0,1605.00,successful,GB,False,49,True
7,Edinburgh Fringe Tour of Two Modern Classics,2550.0,2552.00,successful,GB,False,17,True
8,Forefront Festival 2015,7200.0,7230.00,successful,US,False,68,True
9,Tangerine Theatre presents GODDESS by Serena H...,1200.0,1625.00,successful,GB,False,34,True
10,I Would... get us to Edinburgh!,700.0,745.00,successful,GB,False,27,True
11,Hamlet the Hip-Hopera,9747.0,10103.00,successful,US,True,132,True
12,In The Company Of Women,1987.0,1987.00,successful,GB,False,17,True
13,Interview with a Genius and Half Arsed Flyerer...,230.0,230.00,successful,GB,False,8,True
14,Pride Con,15000.0,15110.00,successful,US,False,60,True
15,En Garde Arts Emerging Artists Festival BOSSS,10000.0,10306.00,successful,US,True,80,True
16,Stacy Queen & Berri Juicy @ Fringe Festival 2016,500.0,610.00,successful,AU,False,12,True
17,"My Life in Michaels, a short play",1200.0,1265.00,successful,US,False,19,True
18,African Celebration!,40000.0,40219.00,successful,NO,False,58,True
19,MSGA Junior Theater Festival 2016,1000.0,1300.00,successful,US,False,17,True
20,A Kingdom for a Stage! - Much Ado...,5000.0,6475.00,successful,US,False,105,True
21,BE BETTER: Urban Foxes - Edinburgh Festival (F...,1300.0,1644.00,successful,GB,False,34,True
22,"Born in Burnley, Made in Edinburgh",1000.0,1132.00,successful,GB,False,51,True
23,SOCKS,1000.0,1420.00,successful,CA,False,29,True
24,CASA Latin American Theatre Festival 2015,7500.0,7503.77,successful,GB,True,117,True
25,Scattered,2500.0,2501.00,successful,GB,False,28,True
26,EUTCo presents scenes from Tom Wells' 'The Kit...,700.0,806.00,successful,GB,False,22,True
27,Two Thirds @ the Edinburgh Fringe Festival,800.0,800.00,successful,GB,False,9,True
28,The Curiositorium at the Edinburgh Fringe 2015,1500.0,1936.99,successful,GB,False,61,True
29,ANTIGONE: An Arabian Tragedy,300.0,375.00,successful,GB,False,5,True
...,...,...,...,...,...,...,...,...
4090,Thérèse Raquin at The Courtyard Theatre,250.0,250.00,successful,GB,False,22,True
4091,The Honeymoon is Over - An Original Play by Za...,900.0,1175.00,successful,US,False,12,True
4092,"""Lucy & Vincente"" A New Play about Lucille Ball",3000.0,3319.00,successful,US,False,43,True
4093,The Lower Depths,2000.0,2287.00,successful,US,False,26,True
4094,Green Light Productions produces theatre creat...,5000.0,5024.00,successful,US,False,41,True
4095,Bluebirds by Joe Brondo,7000.0,7365.00,successful,US,True,75,True
4096,"""Lifted"" - The Theatre Shed's 10 Year Annivers...",2000.0,3100.00,successful,GB,False,78,True
4097,Dandelion Theatre: 'Body Awareness' by Annie B...,2000.0,2041.00,successful,US,False,23,True
4098,"Go People does 'Almost, Maine'",5000.0,5430.00,successful,GB,True,100,True
4099,"One-Man Show: ""The Book Of oded, Chapter 2""",10000.0,10299.00,successful,US,False,162,True
4100,The Seagull Project Presents: The Three Sisters,20000.0,21573.00,successful,US,True,202,True
4101,A Hard Rain - New York Debut,3000.0,3133.00,successful,US,False,28,True
4102,Secret Diaries,2500.0,2867.99,successful,GB,False,95,True
4103,We Rise,1500.0,1800.00,successful,US,False,31,True
4104,Verdigris - A Play by Jim Beaver,35000.0,56079.83,successful,US,True,930,True
4105,The Butterfingers Angel... [By The Mummers],8000.0,8010.00,successful,US,False,113,True
4106,Lord of the Flies - Syracuse University,4000.0,4443.00,successful,US,False,65,True
4107,Beauty and the Beast,4500.0,4592.00,successful,GB,False,63,True
4108,A Few Brave Men: The Chosen Few,5000.0,5000.00,successful,US,False,28,True
4109,Going To Market,2000.0,2100.00,successful,US,False,41,True
4110,LIBERTY! EQUALITY! AND FIREWORKS!... A Civil R...,3000.0,3506.00,successful,US,False,35,True
4111,EUTCo presents 'One Flew Over the Cuckoo's Nest',1000.0,1330.00,successful,GB,False,31,True
4112,CHILD Z,4000.0,4545.00,successful,GB,False,114,True
4113,Saxon Court at Southwark Playhouse,1500.0,1950.00,successful,GB,True,51,True
4114,The Village - one woman show,5000.0,5343.00,successful,CA,False,72,True
4115,Bring Love's Labour's Lost to Minnesota,25000.0,25388.00,successful,US,True,213,True
4116,Score,300.0,340.00,successful,GB,False,17,True
4117,"""The Santaland Diaries"" by David Sedaris in Lo...",6000.0,7140.00,successful,US,False,108,True
4118,REBATEnsemble Presents: ICONS - The Martin Show,300.0,312.00,successful,US,False,6,True
4119,Licensed To Ill,3000.0,3084.00,successful,GB,False,78,True

In [20]:
# Remove projects that made no money at all
clean_df = New_df.loc[(New_df["pledged"] > 0)]
clean_df.head()

,name,goal,pledged,state,country,staff_pick,backers_count,spotlight
0,The Class Act Players Theatre Company Presents...,1500.0,2925.0,successful,US,False,17,True
1,MR INCREDIBLE by Camilla Whitehill - VAULT Fes...,2500.0,2936.0,successful,GB,True,15,True
2,RUN,1000.0,1200.0,successful,GB,False,30,True
3,9th International Meeting of Youth Theatre sap...,2000.0,2135.0,successful,IT,False,24,True
4,Get Conti to the Ed Fringe!,1000.0,1250.0,successful,GB,False,28,True

In [21]:
# Collect only those projects that were hosted in the US
US_df = clean_df.loc[clean_df["country"] == "US", :]
US_df

,name,goal,pledged,state,country,staff_pick,backers_count,spotlight
0,The Class Act Players Theatre Company Presents...,1500.0,2925.00,successful,US,False,17,True
8,Forefront Festival 2015,7200.0,7230.00,successful,US,False,68,True
11,Hamlet the Hip-Hopera,9747.0,10103.00,successful,US,True,132,True
14,Pride Con,15000.0,15110.00,successful,US,False,60,True
15,En Garde Arts Emerging Artists Festival BOSSS,10000.0,10306.00,successful,US,True,80,True
17,"My Life in Michaels, a short play",1200.0,1265.00,successful,US,False,19,True
19,MSGA Junior Theater Festival 2016,1000.0,1300.00,successful,US,False,17,True
20,A Kingdom for a Stage! - Much Ado...,5000.0,6475.00,successful,US,False,105,True
31,Bartleby: a new musical at the MN Fringe,2000.0,2625.00,successful,US,False,25,True
32,"The Point, a show in the Women's Voices Theate...",3150.0,3150.00,successful,US,False,22,True
33,An Intimate Evening With Typhoid Mary,6700.0,7050.00,successful,US,False,102,True
39,"""Poor People"" at FringeNYC 2015",5500.0,5682.00,successful,US,True,34,True
42,Painting His Wings by Sinead Daly at FringeNYC,8000.0,8780.00,successful,US,False,140,True
43,"Lindsay Benner takes ""Book of Love"" to the Edi...",10939.0,13116.00,successful,US,False,160,True
44,Queen Mab's Steampunk and Fairie Street Festival,1300.0,3363.00,successful,US,True,62,True
45,RAFT: a new play by Emily Kitchens,7500.0,7826.00,successful,US,True,120,True
46,butyou'reaman in New York,5000.0,5717.00,successful,US,False,136,True
47,The Spinning Wheel: a son remixes a father's r...,20000.0,22602.00,successful,US,True,228,True
48,bring the children home...,2500.0,2500.00,successful,US,False,46,True
50,Bloomers Presents: LaughtHERfest,8000.0,9501.00,successful,US,True,102,True
52,#liberated,2000.0,2295.00,successful,US,False,62,True
54,Natasha Noman's Noman's Land | Aug 5-15th Edi...,7000.0,7571.00,successful,US,True,84,True
59,COSPLAY,5000.0,5000.00,successful,US,False,42,True
64,Love at the end of time--FringeNYC 2015,5000.0,5055.00,successful,US,False,22,True
67,The Devil You Say,2000.0,4000.00,successful,US,False,67,True
73,Les Midge: An Unexpected Musical of Hobbit Pro...,400.0,407.00,successful,US,False,15,True
74,"""Flying Ship"" Musical by Solo Youth Theater of...",3000.0,3030.00,successful,US,False,60,True
75,West Fulton Puppet Festival,5500.0,5637.00,successful,US,False,53,True
77,Take FLIGHT East to Edinburgh!,4772.0,5661.00,successful,US,False,103,True
79,Ex Communication,2500.0,2710.00,successful,US,False,61,True
...,...,...,...,...,...,...,...,...
4076,MASKS: Off-Broadway Debut,5000.0,5671.11,successful,US,False,53,True
4077,The Impossible Adventures Of Supernova Jones,2000.0,2804.00,successful,US,False,55,True
4078,Kapow-i GoGo at The PIT,2500.0,2575.00,successful,US,True,49,True
4080,"Help us get ""Old Friends"" to the El Portal!!!",3000.0,3160.00,successful,US,False,66,True
4081,The Hurtling Stillness. A story about angels a...,1800.0,1805.00,successful,US,True,12,True
4082,"PL@Y, an all-original fusion of comedy, rock, ...",3000.0,3190.00,successful,US,False,33,True
4083,The Crusade of Connor Stephens: Professional P...,2000.0,2000.00,successful,US,False,15,True
4084,"The Mount, new play about Edith Wharton",2100.0,2305.00,successful,US,False,45,True
4086,Prison Boxing: A New Play by Leah Joki,12200.0,12571.00,successful,US,True,134,True
4087,The Lost Boy (a play),3400.0,4050.00,successful,US,False,23,True
4088,Peter Pan by J.M. Barrie @ Open Space Arts,1000.0,1046.00,successful,US,False,23,True
4091,The Honeymoon is Over - An Original Play by Za...,900.0,1175.00,successful,US,False,12,True
4092,"""Lucy & Vincente"" A New Play about Lucille Ball",3000.0,3319.00,successful,US,False,43,True
4093,The Lower Depths,2000.0,2287.00,successful,US,False,26,True
4094,Green Light Productions produces theatre creat...,5000.0,5024.00,successful,US,False,41,True
4095,Bluebirds by Joe Brondo,7000.0,7365.00,successful,US,True,75,True
4097,Dandelion Theatre: 'Body Awareness' by Annie B...,2000.0,2041.00,successful,US,False,23,True
4099,"One-Man Show: ""The Book Of oded, Chapter 2""",10000.0,10299.00,successful,US,False,162,True
4100,The Seagull Project Presents: The Three Sisters,20000.0,21573.00,successful,US,True,202,True
4101,A Hard Rain - New York Debut,3000.0,3133.00,successful,US,False,28,True
4103,We Rise,1500.0,1800.00,successful,US,False,31,True
4104,Verdigris - A Play by Jim Beaver,35000.0,56079.83,successful,US,True,930,True
4105,The Butterfingers Angel... [By The Mummers],8000.0,8010.00,successful,US,False,113,True
4106,Lord of the Flies - Syracuse University,4000.0,4443.00,successful,US,False,65,True
4108,A Few Brave Men: The Chosen Few,5000.0,5000.00,successful,US,False,28,True
4109,Going To Market,2000.0,2100.00,successful,US,False,41,True
4110,LIBERTY! EQUALITY! AND FIREWORKS!... A Civil R...,3000.0,3506.00,successful,US,False,35,True
4115,Bring Love's Labour's Lost to Minnesota,25000.0,25388.00,successful,US,True,213,True
4117,"""The Santaland Diaries"" by David Sedaris in Lo...",6000.0,7140.00,successful,US,False,108,True
4118,REBATEnsemble Presents: ICONS - The Martin Show,300.0,312.00,successful,US,False,6,True

In [24]:
# Create a new column that finds the average amount pledged to a project
US_df["average_donation"] = US_df["pledged"] / US_df["backers_count"]
US_df

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

,name,goal,pledged,state,country,staff_pick,backers_count,spotlight,Average Pledged,average_donation
0,The Class Act Players Theatre Company Presents...,1500.0,2925.00,successful,US,False,17,True,1.950000,172.058824
8,Forefront Festival 2015,7200.0,7230.00,successful,US,False,68,True,1.004167,106.323529
11,Hamlet the Hip-Hopera,9747.0,10103.00,successful,US,True,132,True,1.036524,76.537879
14,Pride Con,15000.0,15110.00,successful,US,False,60,True,1.007333,251.833333
15,En Garde Arts Emerging Artists Festival BOSSS,10000.0,10306.00,successful,US,True,80,True,1.030600,128.825000
17,"My Life in Michaels, a short play",1200.0,1265.00,successful,US,False,19,True,1.054167,66.578947
19,MSGA Junior Theater Festival 2016,1000.0,1300.00,successful,US,False,17,True,1.300000,76.470588
20,A Kingdom for a Stage! - Much Ado...,5000.0,6475.00,successful,US,False,105,True,1.295000,61.666667
31,Bartleby: a new musical at the MN Fringe,2000.0,2625.00,successful,US,False,25,True,1.312500,105.000000
32,"The Point, a show in the Women's Voices Theate...",3150.0,3150.00,successful,US,False,22,True,1.000000,143.181818
33,An Intimate Evening With Typhoid Mary,6700.0,7050.00,successful,US,False,102,True,1.052239,69.117647
39,"""Poor People"" at FringeNYC 2015",5500.0,5682.00,successful,US,True,34,True,1.033091,167.117647
42,Painting His Wings by Sinead Daly at FringeNYC,8000.0,8780.00,successful,US,False,140,True,1.097500,62.714286
43,"Lindsay Benner takes ""Book of Love"" to the Edi...",10939.0,13116.00,successful,US,False,160,True,1.199013,81.975000
44,Queen Mab's Steampunk and Fairie Street Festival,1300.0,3363.00,successful,US,True,62,True,2.586923,54.241935
45,RAFT: a new play by Emily Kitchens,7500.0,7826.00,successful,US,True,120,True,1.043467,65.216667
46,butyou'reaman in New York,5000.0,5717.00,successful,US,False,136,True,1.143400,42.036765
47,The Spinning Wheel: a son remixes a father's r...,20000.0,22602.00,successful,US,True,228,True,1.130100,99.131579
48,bring the children home...,2500.0,2500.00,successful,US,False,46,True,1.000000,54.347826
50,Bloomers Presents: LaughtHERfest,8000.0,9501.00,successful,US,True,102,True,1.187625,93.147059
52,#liberated,2000.0,2295.00,successful,US,False,62,True,1.147500,37.016129
54,Natasha Noman's Noman's Land | Aug 5-15th Edi...,7000.0,7571.00,successful,US,True,84,True,1.081571,90.130952
59,COSPLAY,5000.0,5000.00,successful,US,False,42,True,1.000000,119.047619
64,Love at the end of time--FringeNYC 2015,5000.0,5055.00,successful,US,False,22,True,1.011000,229.772727
67,The Devil You Say,2000.0,4000.00,successful,US,False,67,True,2.000000,59.701493
73,Les Midge: An Unexpected Musical of Hobbit Pro...,400.0,407.00,successful,US,False,15,True,1.017500,27.133333
74,"""Flying Ship"" Musical by Solo Youth Theater of...",3000.0,3030.00,successful,US,False,60,True,1.010000,50.500000
75,West Fulton Puppet Festival,5500.0,5637.00,successful,US,False,53,True,1.024909,106.358491
77,Take FLIGHT East to Edinburgh!,4772.0,5661.00,successful,US,False,103,True,1.186295,54.961165
79,Ex Communication,2500.0,2710.00,successful,US,False,61,True,1.084000,44.426230
...,...,...,...,...,...,...,...,...,...,...
4076,MASKS: Off-Broadway Debut,5000.0,5671.11,successful,US,False,53,True,1.134222,107.002075
4077,The Impossible Adventures Of Supernova Jones,2000.0,2804.00,successful,US,False,55,True,1.402000,50.981818
4078,Kapow-i GoGo at The PIT,2500.0,2575.00,successful,US,True,49,True,1.030000,52.551020
4080,"Help us get ""Old Friends"" to the El Portal!!!",3000.0,3160.00,successful,US,False,66,True,1.053333,47.878788
4081,The Hurtling Stillness. A story about angels a...,1800.0,1805.00,successful,US,True,12,True,1.002778,150.416667
4082,"PL@Y, an all-original fusion of comedy, rock, ...",3000.0,3190.00,successful,US,False,33,True,1.063333,96.666667
4083,The Crusade of Connor Stephens: Professional P...,2000.0,2000.00,successful,US,False,15,True,1.000000,133.333333
4084,"The Mount, new play about Edith Wharton",2100.0,2305.00,successful,US,False,45,True,1.097619,51.222222
4086,Prison Boxing: A New Play by Leah Joki,12200.0,12571.00,successful,US,True,134,True,1.030410,93.813433
4087,The Lost Boy (a play),3400.0,4050.00,successful,US,False,23,True,1.191176,176.086957
4088,Peter Pan by J.M. Barrie @ Open Space Arts,1000.0,1046.00,successful,US,False,23,True,1.046000,45.478261
4091,The Honeymoon is Over - An Original Play by Za...,900.0,1175.00,successful,US,False,12,True,1.305556,97.916667
4092,"""Lucy & Vincente"" A New Play about Lucille Ball",3000.0,3319.00,successful,US,False,43,True,1.106333,77.186047
4093,The Lower Depths,2000.0,2287.00,successful,US,False,26,True,1.143500,87.961538
4094,Green Light Productions produces theatre creat...,5000.0,5024.00,successful,US,False,41,True,1.004800,122.536585
4095,Bluebirds by Joe Brondo,7000.0,7365.00,successful,US,True,75,True,1.052143,98.200000
4097,Dandelion Theatre: 'Body Awareness' by Annie B...,2000.0,2041.00,successful,US,False,23,True,1.020500,88.739130
4099,"One-Man Show: ""The Book Of oded, Chapter 2""",10000.0,10299.00,successful,US,False,162,True,1.029900,63.574074
4100,The Seagull Project Presents: The Three Sisters,20000.0,21573.00,successful,US,True,202,True,1.078650,106.797030
4101,A Hard Rain - New York Debut,3000.0,3133.00,successful,US,False,28,True,1.044333,111.892857
4103,We Rise,1500.0,1800.00,successful,US,False,31,True,1.200000,58.064516
4104,Verdigris - A Play by Jim Beaver,35000.0,56079.83,successful,US,True,930,True,1.602281,60.300892
4105,The Butterfingers Angel... [By The Mummers],8000.0,8010.00,successful,US,False,113,True,1.001250,70.884956
4106,Lord of the Flies - Syracuse University,4000.0,4443.00,successful,US,False,65,True,1.110750,68.353846
4108,A Few Brave Men: The Chosen Few,5000.0,5000.00,successful,US,False,28,True,1.000000,178.571429
4109,Going To Market,2000.0,2100.00,successful,US,False,41,True,1.050000,51.219512
4110,LIBERTY! EQUALITY! AND FIREWORKS!... A Civil R...,3000.0,3506.00,successful,US,False,35,True,1.168667,100.171429
4115,Bring Love's Labour's Lost to Minnesota,25000.0,25388.00,successful,US,True,213,True,1.015520,119.192488
4117,"""The Santaland Diaries"" by David Sedaris in Lo...",6000.0,7140.00,successful,US,False,108,True,1.190000,66.111111
4118,REBATEnsemble Presents: ICONS - The Martin Show,300.0,312.00,successful,US,False,6,True,1.040000,52.000000

In [25]:
# First convert "average_donation", "goal", and "pledged" columns to float
US_df["average_donation"] = US_df["average_donation"].astype(float).map("${:,.2f}".format)
US_df["goal"] = US_df["goal"].astype(float).map("${:,.2f}".format)
US_df["pledged"] = US_df["pledged"].astype(float).map("${:,.2f}".format)
US_df.dtypes
# Then Format to go to two decimal places, include a dollar sign, and use comma notation
US_df.head()

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,name,goal,pledged,state,country,staff_pick,backers_count,spotlight,Average Pledged,average_donation
0,The Class Act Players Theatre Company Presents...,"$1,500.00","$2,925.00",successful,US,False,17,True,1.950000,$172.06
8,Forefront Festival 2015,"$7,200.00","$7,230.00",successful,US,False,68,True,1.004167,$106.32
11,Hamlet the Hip-Hopera,"$9,747.00","$10,103.00",successful,US,True,132,True,1.036524,$76.54
14,Pride Con,"$15,000.00","$15,110.00",successful,US,False,60,True,1.007333,$251.83
15,En Garde Arts Emerging Artists Festival BOSSS,"$10,000.00","$10,306.00",successful,US,True,80,True,1.030600,$128.82

In [26]:
# Calculate the total number of backers for all US projects
US_df["backers_count"].sum()

89273

In [27]:
# Calculate the average number of backers for all US projects
US_df["backers_count"].mean()

41.931892907468296

In [28]:
# Collect only those US campaigns that have been picked as a "Staff Pick"
picked_by_staff = US_df.loc[US_df["staff_pick"] == True]
picked_by_staff

,name,goal,pledged,state,country,staff_pick,backers_count,spotlight,Average Pledged,average_donation
11,Hamlet the Hip-Hopera,"$9,747.00","$10,103.00",successful,US,True,132,True,1.036524,$76.54
15,En Garde Arts Emerging Artists Festival BOSSS,"$10,000.00","$10,306.00",successful,US,True,80,True,1.030600,$128.82
39,"""Poor People"" at FringeNYC 2015","$5,500.00","$5,682.00",successful,US,True,34,True,1.033091,$167.12
44,Queen Mab's Steampunk and Fairie Street Festival,"$1,300.00","$3,363.00",successful,US,True,62,True,2.586923,$54.24
45,RAFT: a new play by Emily Kitchens,"$7,500.00","$7,826.00",successful,US,True,120,True,1.043467,$65.22
47,The Spinning Wheel: a son remixes a father's r...,"$20,000.00","$22,602.00",successful,US,True,228,True,1.130100,$99.13
50,Bloomers Presents: LaughtHERfest,"$8,000.00","$9,501.00",successful,US,True,102,True,1.187625,$93.15
54,Natasha Noman's Noman's Land | Aug 5-15th Edi...,"$7,000.00","$7,571.00",successful,US,True,84,True,1.081571,$90.13
107,Peter/Wendy goes to the 2015 Edinburgh Fringe ...,"$10,000.00","$12,003.00",successful,US,True,95,True,1.200300,$126.35
115,La Lune de Femme goes to New Orleans Fringe,"$5,000.00","$5,519.00",successful,US,True,79,True,1.103800,$69.86
117,Secular Solstice 2014,"$7,500.00","$8,157.01",successful,US,True,164,True,1.087601,$49.74
122,Southern Shakespeare Festival,"$7,500.00","$8,202.00",successful,US,True,63,True,1.093600,$130.19
128,Too Much Light Heads to the Edinburgh Fringe!,"$15,000.00","$15,277.00",successful,US,True,239,True,1.018467,$63.92
136,And Then Came Tango,"$2,000.00","$2,001.00",successful,US,True,39,True,1.000500,$51.31
153,The Trouble With Dead Boyfriends goes to Premi...,"$4,500.00","$4,970.00",successful,US,True,79,True,1.104444,$62.91
194,(Wo)men Rule Broadway,"$10,000.00","$10,034.00",successful,US,True,50,True,1.003400,$200.68
215,The Waterman: A Forgotten Cascadian Myth,"$3,500.00","$3,502.50",successful,US,True,66,True,1.000714,$53.07
226,TINY - A New Musical Based On The Life Of Tiny...,"$7,500.00","$9,591.00",successful,US,True,138,True,1.278800,$69.50
228,Deaf West Theatre's Spring Awakening Tony Perf...,"$200,000.00","$211,634.17",successful,US,True,1769,True,1.058171,$119.63
252,The Wolves of Chernobyl Present Recordings & T...,"$3,150.00","$4,658.00",successful,US,True,125,True,1.478730,$37.26
254,Alien Vs. Musical,"$15,000.00","$16,212.00",successful,US,True,371,True,1.080800,$43.70
260,Help Get Street Theatre Off The Street,"$15,000.00","$16,612.00",successful,US,True,119,True,1.107467,$139.60
264,He Knew He Would Say It (But Could He Believe ...,"$5,000.00","$5,916.00",successful,US,True,70,True,1.183200,$84.51
276,"35MM, A Musical Exhibition","$5,000.00","$5,030.00",successful,US,True,35,True,1.006000,$143.71
278,SPEAKEASY - a new musical,"$13,500.00","$14,305.00",successful,US,True,142,True,1.059630,$100.74
286,The Monster of Phantom Lake: The Musical!,"$2,500.00","$6,495.00",successful,US,True,103,True,2.598000,$63.06
288,Kat Robichaud's Misfit Cabaret,"$6,000.00","$12,141.69",successful,US,True,179,True,2.023615,$67.83
293,Spies Are Forever: A New Comedy Musical,"$42,000.00","$58,830.08",successful,US,True,1147,True,1.400716,$51.29
314,"Andina, the Opera That Never Was","$2,200.00","$5,076.89",successful,US,True,91,True,2.307677,$55.79
321,'What's Your Wish?'- Thicket & Thistle's Fring...,"$6,750.00","$6,766.83",successful,US,True,101,True,1.002493,$67.00
...,...,...,...,...,...,...,...,...,...,...
3660,"Toscana, or What I Remember","$4,000.00","$4,296.00",successful,US,True,21,True,1.074000,$204.57
3702,Catapult OYL to the next level—in Edinburgh!,"$15,000.00","$15,481.00",successful,US,True,181,True,1.032067,$85.53
3716,"Two ""Gentlemen"" of Verona by William Shakespeare","$2,000.00","$2,047.00",successful,US,True,39,True,1.023500,$52.49
3741,Honorable Men - Poor Yorick's Players 2016 Season,"$1,000.00","$1,312.00",successful,US,True,26,True,1.312000,$50.46
3811,Orpheus Descending by Tennessee Williams,"$15,500.00","$15,705.00",successful,US,True,286,True,1.013226,$54.91
3821,Hear Me Roar: A Season of Powerful Women,"$7,000.00","$7,164.00",successful,US,True,37,True,1.023429,$193.62
3827,"""Next Stop"" - Adjusting to dating in NYC","$10,000.00","$15,443.00",successful,US,True,145,True,1.544300,$106.50
3828,Titus Andronicus (with an all-female cast & crew),"$2,500.00","$2,804.16",successful,US,True,68,True,1.121664,$41.24
3838,Keep the Art of Marionettes Alive With PUPPETW...,"$5,000.00","$5,462.00",successful,US,True,73,True,1.092400,$74.82
3846,Shakespeare in ASL - and FREE for everyone,"$2,500.00","$3,120.00",successful,US,True,84,True,1.248000,$37.14
3866,Celebrating 20 years of The 24 Hour Plays arou...,"$35,000.00","$35,275.64",successful,US,True,269,True,1.007875,$131.14
3871,THE INCREDIBLE FOX SISTERS,"$8,000.00","$8,227.00",successful,US,True,71,True,1.028375,$115.87
3876,Colt Coeur's 6th Season,"$35,000.00","$35,123.00",successful,US,True,134,True,1.003514,$262.11
3883,The Gray Man,"$10,000.00","$11,122.00",successful,US,True,193,True,1.112200,$57.63
3899,Good People by David Lindsay-Abaire at Waterfr...,"$3,100.00","$3,395.00",successful,US,True,74,True,1.095161,$45.88
3926,Scrappy Shakespeare: A Midsummer Night's Dream,"$3,300.00","$3,315.00",successful,US,True,49,True,1.004545,$67.65
3929,"or, The Whale: an original stage adaptation of...","$15,000.00","$15,315.00",successful,US,True,288,True,1.021000,$53.18
3951,Paperhand Puppet Intervention 16th Annual Summ...,"$10,000.00","$12,806.00",successful,US,True,176,True,1.280600,$72.76
3952,"Yesterday Again, Please - A New Play by Dezi G...","$5,500.00","$5,771.00",successful,US,True,88,True,1.049273,$65.58
3954,The Metronome Society,"$1,500.00","$1,661.00",successful,US,True,20,True,1.107333,$83.05
3970,Macbeth,"$6,000.00","$7,877.00",successful,US,True,163,True,1.312833,$48.33
4018,Honest Accomplice Theatre 2015-16 Season,"$12,000.00","$12,095.00",successful,US,True,200,True,1.007917,$60.48
4049,Eyes Closed - The First In-Dream Theater Exper...,"$20,000.00","$20,022.00",successful,US,True,119,True,1.001100,$168.25
4078,Kapow-i GoGo at The PIT,"$2,500.00","$2,575.00",successful,US,True,49,True,1.030000,$52.55
4081,The Hurtling Stillness. A story about angels a...,"$1,800.00","$1,805.00",successful,US,True,12,True,1.002778,$150.42
4086,Prison Boxing: A New Play by Leah Joki,"$12,200.00","$12,571.00",successful,US,True,134,True,1.030410,$93.81
4095,Bluebirds by Joe Brondo,"$7,000.00","$7,365.00",successful,US,True,75,True,1.052143,$98.20
4100,The Seagull Project Presents: The Three Sisters,"$20,000.00","$21,573.00",successful,US,True,202,True,1.078650,$106.80
4104,Verdigris - A Play by Jim Beaver,"$35,000.00","$56,079.83",successful,US,True,930,True,1.602281,$60.30
4115,Bring Love's Labour's Lost to Minnesota,"$25,000.00","$25,388.00",successful,US,True,213,True,1.015520,$119.19

In [29]:
# Group by the state of the campaigns and see if staff picks matter (Seems to matter quite a bit)
state_groups = picked_by_staff.groupby("state")
state_groups["name"].count()

state
canceled        6
failed         21
live            2
successful    145
Name: name, dtype: int64